name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: commit messages joined
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, '; ') }}
        run: echo "$COMMIT_MESSAGES"
      - name: bump version and push tag
        if: ${{ github.event_name == 'push' && false == contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: set node.js up
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint code
        run: npm run eslint
      - name: build code
        run: npm run build
      - name: test code
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          # start: npm run start-prod
          start: npm run start
          wait-on: 'http://localhost:5000'
      - name: build/tests failed message
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_URL }}
      - name: deploy code
        if: ${{ github.event_name == 'push' && false == contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'mooc-part11'
          heroku_email: 'jukkaa@live.com'
          healthcheck: 'https://mooc-part11.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true
      - name: job was successful message
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,author,took
          custom_payload: |
           {
             attachments: [{
               color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
               text: `A new version was deployed to https://mooc-part11.herokuapp.com/ with commit ${process.env.AS_COMMIT} of ${process.env.AS_REPO} by ${process.env.AS_AUTHOR} and build took ${process.env.AS_TOOK}`
             }]
           }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_URL }}
