name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: bump version and push tag
        if: ${{ github.event_name == 'push' && false == contains(toJson(github.event.commits.*.messages), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: set node.js up
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint code
        run: npm run eslint
      - name: build code
        run: npm run build
      - name: test code
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'
      - name: deploy code
        if: ${{ github.event_name == 'push' && false == contains(toJson(github.event.commits.*.messages), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'mooc-part11'
          heroku_email: 'jukkaa@live.com'
          healthcheck: 'https://mooc-part11.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true
