# name: Testing G-Actions stuff

# on:
#   push:
#     branches:
#       - feature

# jobs:
#   a_test_job_v5:
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: commits with if
#         if: ${{ false == contains(toJson(github.event.commits.*.message), '#skip') }}
#         env:
#           COMMITS: ${{ toJson(github.event.commits) }}
#         run: echo "$COMMITS"
#       - name: commit messages joined
#         env:
#           COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, '; ') }}
#         run: echo "$COMMIT_MESSAGES"
